### ISSUE TITLE
I can't find InitString()

### ISSUE THREAD

**Issue by ACLzz** [dimiro1/banner#6]
Hello, I want to use your lib to add banner to my program, but when I trying to run your `title` example, go can't find `InitString` method and GoLand shows only `Init` and `SetLog` methods. Also, if I try to replace `InitString` with `Init` and convert `templ` to bytes, like in your quickstart, it just don't show anything.

Strange cause I downloaded your repo now and with your repo it works, maybe cause my go 1.15 version? I see 1.11 in your go.mod

**Comment by dimiro1** [comment]
That is very strange. The `InitString` function can be found in `banner.go` file. https://github.com/dimiro1/banner/blob/master/banner.go#L75

**Comment by el-ideal-ideas** [comment]
Hi
I have the same problem.
I can't find InitString() in `banner.go`
I use `go get github.com/dimiro1/banner`
My `banner.go` is different from `banner.go` in your github.
I don't know why.

**Comment by dimiro1** [comment]
You both are using an old release. I just issued a new version [v1.1.0] that will address this issue.
