### ISSUE TITLE
using banner with new version of golang 

### ISSUE THREAD

**Issue by Soneca-ii** [dimiro1/banner#7]
Hi,

Using banner in my project with golang 15 it works perfectly for app execution but fails when trying to write tests:

"flag provided but not defined: -test.testlogfile"

this is due to 	flag.Parse() in autoload.go.

Is there some workaround to use the banner with newer versions of golang?

**Comment by dimiro1** [comment]
@Soneca-ii Could you provide a sample script that replicates the issue?

**Comment by Soneca-ii** [comment]
Executing it shows correctly the banner:

App
GoVersion: go1.15.10
GOOS: windows
GOARCH: amd64
NumCPU: 8
GOPATH: XXXX\go
GOROOT: XXXX\go\go1.15.10
Compiler: gc
ENV: XXXXX\go
Now: Thursday, 25 Mar 2021
Process finished with the exit code 0

Executing the test ( i'm using IntelliJ ultimate ide )


GOROOT=XXX\go\go1.15.10 #gosetup
GOPATH=XXX\go #gosetup
XXX\go\go1.15.10\bin\go.exe test -json ./src/... #gosetup
flag provided but not defined: -test.testlogfile
Usage of XXXX\AppData\Local\Temp\go-build842786182\b001\src.test.exe:
  -ansi
    	ansi colors enabled? (default true)
  -banner string
    	banner.txt file (default "banner.txt")
  -show-banner
    	print the banner? (default true)
FAIL	banner_test/src	0.734s


Process finished with the exit code 1


 
[banner_test.zip](https://github.com/dimiro1/banner/files/6203954/banner_test.zip)

**Comment by dimiro1** [comment]
Thank you for providing an example, I will take a look later.

**Comment by bilalcaliskan** [comment]
@Soneca-ii i made it work similar problem with banner API as shown [here](https://github.com/bilalcaliskan/syn-flood/blob/master/cmd/syn-flood/main.go#L14)

**Comment by dimiro1** [comment]
You need to use the autoload feature, you can just use the banner API directly, e.g: https://github.com/dimiro1/banner/blob/master/autoload/autoload.go#L17
